//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Home", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abre en ventana nueva.
        /// </summary>
        internal static string AbreVentanaNueva {
            get {
                return ResourceManager.GetString("AbreVentanaNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARrastrar y soltar, con ratón y nada más.
        /// </summary>
        internal static string ArrastrarYSoltar {
            get {
                return ResourceManager.GetString("ArrastrarYSoltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsive. Caixabank, un buen ejemplo.
        /// </summary>
        internal static string CaixaBank {
            get {
                return ResourceManager.GetString("CaixaBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con estructura.
        /// </summary>
        internal static string ConEstructura {
            get {
                return ResourceManager.GetString("ConEstructura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demostraciones.
        /// </summary>
        internal static string Demostraciones {
            get {
                return ResourceManager.GetString("Demostraciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divs para todo:.
        /// </summary>
        internal static string DivsParaTodo {
            get {
                return ResourceManager.GetString("DivsParaTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to divs tuneados para que funcionen como enlaces y botones.
        /// </summary>
        internal static string DivsTuneados {
            get {
                return ResourceManager.GetString("DivsTuneados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlaces sorpresa, como los kinder.
        /// </summary>
        internal static string EnlacesSorpresa {
            get {
                return ResourceManager.GetString("EnlacesSorpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlaces y botones que no son lo que parecen.
        /// </summary>
        internal static string EnlacesYBotones {
            get {
                return ResourceManager.GetString("EnlacesYBotones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estructura:.
        /// </summary>
        internal static string Estructura {
            get {
                return ResourceManager.GetString("Estructura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulario accesible.
        /// </summary>
        internal static string FormularioAccesible {
            get {
                return ResourceManager.GetString("FormularioAccesible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulario no accesible.
        /// </summary>
        internal static string FormularioNoAccesible {
            get {
                return ResourceManager.GetString("FormularioNoAccesible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formularios.
        /// </summary>
        internal static string Formularios {
            get {
                return ResourceManager.GetString("Formularios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imágenes sin etiquetar.
        /// </summary>
        internal static string ImagenesSinEtiquetar {
            get {
                return ResourceManager.GetString("ImagenesSinEtiquetar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        internal static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejemplo de web con buena estructura (justeat).
        /// </summary>
        internal static string Justeat {
            get {
                return ResourceManager.GetString("Justeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Miénteme!.
        /// </summary>
        internal static string Mienteme {
            get {
                return ResourceManager.GetString("Mienteme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si haces ruido, se jodió el oído.
        /// </summary>
        internal static string Ruido {
            get {
                return ResourceManager.GetString("Ruido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin estructura.
        /// </summary>
        internal static string SinEstructura {
            get {
                return ResourceManager.GetString("SinEstructura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo que se ve no es lo que se escucha.
        /// </summary>
        internal static string VerYEscuchar {
            get {
                return ResourceManager.GetString("VerYEscuchar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo que se ve no es lo que se escucha (revival).
        /// </summary>
        internal static string VerYEscucharRevival {
            get {
                return ResourceManager.GetString("VerYEscucharRevival", resourceCulture);
            }
        }
    }
}
