//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Estructura {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Estructura() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Estructura", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Y qué debería hacer?.
        /// </summary>
        internal static string ComoHacerloBien {
            get {
                return ResourceManager.GetString("ComoHacerloBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con estructura.
        /// </summary>
        internal static string ConEstructura {
            get {
                return ResourceManager.GetString("ConEstructura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porque se usan encabezados de verdad.
        /// </summary>
        internal static string EncabezadosDeVerdad {
            get {
                return ResourceManager.GetString("EncabezadosDeVerdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Por qué esto no está bien?.
        /// </summary>
        internal static string EstoNoEstaBien {
            get {
                return ResourceManager.GetString("EstoNoEstaBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Por qué esto sí está bien?.
        /// </summary>
        internal static string EstructuraBien {
            get {
                return ResourceManager.GetString("EstructuraBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se usan encabezados de verdad.
        /// </summary>
        internal static string FalsosEncabezados {
            get {
                return ResourceManager.GetString("FalsosEncabezados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡No! ¡NO la líes, que lo estabas haciendo muy bien!.
        /// </summary>
        internal static string HazloBien {
            get {
                return ResourceManager.GetString("HazloBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menú.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer ítem.
        /// </summary>
        internal static string PrimerItem {
            get {
                return ResourceManager.GetString("PrimerItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo ítem.
        /// </summary>
        internal static string SegundoItem {
            get {
                return ResourceManager.GetString("SegundoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin estructura.
        /// </summary>
        internal static string SinEstructura {
            get {
                return ResourceManager.GetString("SinEstructura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tercer ítem.
        /// </summary>
        internal static string TercerItem {
            get {
                return ResourceManager.GetString("TercerItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿No puedo usar solo divs y ya? ¡Si se va a ver igual!.
        /// </summary>
        internal static string UsarDivs {
            get {
                return ResourceManager.GetString("UsarDivs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Pues usarlos, que para eso están!.
        /// </summary>
        internal static string Usarlos {
            get {
                return ResourceManager.GetString("Usarlos", resourceCulture);
            }
        }
    }
}
