//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Forms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Forms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Forms", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los apellidos son obligatorios..
        /// </summary>
        internal static string ApellidosObligatorios {
            get {
                return ResourceManager.GetString("ApellidosObligatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entre 10 y 20.
        /// </summary>
        internal static string DiezVeinte {
            get {
                return ResourceManager.GetString("DiezVeinte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        internal static string Enviar {
            get {
                return ResourceManager.GetString("Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulario accesible.
        /// </summary>
        internal static string FormAccesible {
            get {
                return ResourceManager.GetString("FormAccesible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulario no accesible.
        /// </summary>
        internal static string FormNoAccesible {
            get {
                return ResourceManager.GetString("FormNoAccesible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos:.
        /// </summary>
        internal static string LblApellidos {
            get {
                return ResourceManager.GetString("LblApellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre:.
        /// </summary>
        internal static string LblNombre {
            get {
                return ResourceManager.GetString("LblNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre es obligatorio..
        /// </summary>
        internal static string NombreObligatorio {
            get {
                return ResourceManager.GetString("NombreObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rango de edad:.
        /// </summary>
        internal static string RangoEdad {
            get {
                return ResourceManager.GetString("RangoEdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisa los siguientes errores:.
        /// </summary>
        internal static string RevisarErrores {
            get {
                return ResourceManager.GetString("RevisarErrores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entre 30 y 40.
        /// </summary>
        internal static string TreintaCuarenta {
            get {
                return ResourceManager.GetString("TreintaCuarenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entre 20 y 30.
        /// </summary>
        internal static string VeinteTreinta {
            get {
                return ResourceManager.GetString("VeinteTreinta", resourceCulture);
            }
        }
    }
}
