//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Idiomas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idiomas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Idiomas", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este es un texto que el lector de pantallas lee con acento inglés, porque el idioma de la página está mal marcado..
        /// </summary>
        internal static string TextoCastellano {
            get {
                return ResourceManager.GetString("TextoCastellano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dependency injection.
        /// </summary>
        internal static string TextoIngles {
            get {
                return ResourceManager.GetString("TextoIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un patrón muy utilizado es el patrón de inyección de dependencia, en inglés llamado ({0})..
        /// </summary>
        internal static string TextoPalabrasIngles {
            get {
                return ResourceManager.GetString("TextoPalabrasIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma de la página bien marcado.
        /// </summary>
        internal static string TituloBien {
            get {
                return ResourceManager.GetString("TituloBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma de la página mal ajustado.
        /// </summary>
        internal static string TituloMal {
            get {
                return ResourceManager.GetString("TituloMal", resourceCulture);
            }
        }
    }
}
