//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Interfaz {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Interfaz() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Interfaz", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo que.
        /// </summary>
        internal static string Desordenado1 {
            get {
                return ResourceManager.GetString("Desordenado1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intento demostrar.
        /// </summary>
        internal static string Desordenado2 {
            get {
                return ResourceManager.GetString("Desordenado2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es que el.
        /// </summary>
        internal static string Desordenado3 {
            get {
                return ResourceManager.GetString("Desordenado3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOM y el flujo visual de.
        /// </summary>
        internal static string Desordenado4 {
            get {
                return ResourceManager.GetString("Desordenado4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to una web no .
        /// </summary>
        internal static string Desordenado5 {
            get {
                return ResourceManager.GetString("Desordenado5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to están relacionados.
        /// </summary>
        internal static string Desordenado6 {
            get {
                return ResourceManager.GetString("Desordenado6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola..
        /// </summary>
        internal static string DesordenadoHola {
            get {
                return ResourceManager.GetString("DesordenadoHola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to llamo.
        /// </summary>
        internal static string DesordenadoLlamo {
            get {
                return ResourceManager.GetString("DesordenadoLlamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        internal static string DesordenadoMe {
            get {
                return ResourceManager.GetString("DesordenadoMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juanjo..
        /// </summary>
        internal static string DesordenadoNombre {
            get {
                return ResourceManager.GetString("DesordenadoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Hombre, Juanjo! ¡Es un placer tenerte entre nosotros! ¡Eres un crack!.
        /// </summary>
        internal static string JuanjoCAeBien {
            get {
                return ResourceManager.GetString("JuanjoCAeBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A todos nos cae mal Juanjo. Es un petardo y no tiene ni idea de accesibilidad. ¡Y además su perro es muy feo!.
        /// </summary>
        internal static string JuanjoCaeMal {
            get {
                return ResourceManager.GetString("JuanjoCaeMal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Miénteme!.
        /// </summary>
        internal static string Mienteme {
            get {
                return ResourceManager.GetString("Mienteme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo que se ve no es lo que se escucha.
        /// </summary>
        internal static string VerYEscuchar {
            get {
                return ResourceManager.GetString("VerYEscuchar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo que se ve no es lo que se escucha (revival).
        /// </summary>
        internal static string VerYEscucharRevival {
            get {
                return ResourceManager.GetString("VerYEscucharRevival", resourceCulture);
            }
        }
    }
}
